# Book settings (https://jupyterbook.org/customize/config.html)
title: State of Open Source AI Book
author: Prem
copyright: CC-BY-4.0 (text) & Apache-2.0 (code)
logo: https://static.premai.io/logo.png
repository:
  url: https://github.com/premAI-io/state-of-open-source-ai
  branch: main
only_build_toc_files: true
exclude_patterns: [.github/*]
html:
  baseurl: http://localhost:8000
  favicon: assets/favicon.ico
  use_edit_page_button: true
  use_repository_button: true
  announcement: ⚠️ work in progress; please don't share externally
  comments:
    utterances:
      issue-term: pathname
      label: question
      repo: premAI-io/state-of-open-source-ai
      theme: preferred-color-scheme
parse:
  myst_substitutions:
    baseurl: http://localhost:8000
    wip_chapter: |
      This chapter is still being written & reviewed. Please do post links & discussion in the {{
        '[<i class="fas fa-pencil-alt"></i> comments]({}-comments)'.format(env.docname) }} below, or {{
        '[<i class="fab fa-github"></i> open a pull request]({}/edit/main/{}.md)'.format(
        env.config.html_theme_options.repository_url, env.docname)
      }}!
    table_feedback: |
      ```{admonition} Feedback
      :class: attention
      Is the table above outdated or missing an important model? Let us know in the {{
        '[<i class="fas fa-pencil-alt"></i> comments]({}-comments)'.format(env.docname) }} below, or {{
        '[<i class="fab fa-github"></i> open a pull request]({}/edit/main/{}.md)'.format(
        env.config.html_theme_options.repository_url, env.docname)
      }}!
      ```
    comments: |
      {{ '({}-comments)='.format(env.docname) }}

      ```{admonition} Feedback
      :class: attention
      Missing something important? Let us know in the comments below, or {{
        '[<i class="fab fa-github"></i> open a pull request]({}/edit/main/{}.md)'.format(
        env.config.html_theme_options.repository_url, env.docname)
      }}!
      ```

      % hack to get utteranc.es to render (needs a `div.section` element)
      <div class="section"></div>

      {{ '```{committers} ' + env.docname + '.md\n```' }}

      <div id="email-modal" class="modal">
        <div class="modal-content">
          <!--<div class="header"><span class="close">&times;</span></div>-->
          <label for="name">To access this book for free, please enter your email. We won't spam you!</label>
          <input type="email" id="email" name="email" />
          <button id="email-submit" onclick="emailButtonClick()">Submit</button>
          <span class="email-error"></span>
        </div>
      </div>
  myst_enable_extensions: # https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html
  # needs myst-parser>=0.19 <- https://github.com/executablebooks/MyST-NB/issues/530
  #- attrs_block
  #- attrs_inline
  - deflist
  - dollarmath
  - html_admonition
  - linkify
  - replacements
  - smartquotes
  - substitution
  - tasklist
sphinx:
  extra_extensions:
  - sphinxemoji.sphinxemoji
  - sphinx_last_updated_by_git
  - sphinx_subfigure
  # custom (local *.py files)
  - badges
  - committers
  - bibliography
  config:
    myst_heading_anchors: 4
    html_js_files:
    - [https://analytics.prem.ninja/js/script.js, {defer: defer, data-domain: book.premai.io}]
    linkcheck_ignore:
    - http://localhost:8000
    # GitHub anchors
    - https://github.com/\w+/\w+/blob/\w+/.*#L\d+(-L\d+)?
    - https://github.com/premAI-io/prem-app#.*
    - https://github.com/BlinkDL/RWKV-LM#.*
    - https://github.com/CompVis/stable-diffusion/blob/main/Stable_Diffusion_v1_Model_Card.md#.*
    - https://github.com/ggerganov/ggml#.*
    - https://github.com/huggingface/optimum#.*
    - https://github.com/imaurer/awesome-decentralized-llm#.*
    - https://github.com/kingoflolz/mesh-transformer-jax#.*
    - https://github.com/lm-sys/FastChat.*#.*
    - https://github.com/onnx/onnx-tensorrt/blob/main/docs/operators.md#.*
    - https://github.com/onnx/onnx-tensorrt#.*
    - https://github.com/onnx/tutorials#.*
    - https://gist.github.com/veekaybee/be375ab33085102f9027853128dc5f0e#.*
    # misc
    - https://www.nytimes.com/2016/04/19/technology/google-books-case.html
    - https://doi.org/10.2307/2214413
    - https://github.com/premAI-io/state-of-open-source-ai # TODO: remove
    - https://contrib.rocks # TODO: remove
    - https://direct.mit.edu/daed/article/151/2/127/110621/Human-Language-Understanding-amp-Reasoning
    - https://numfocus.org
    - https://chat.openai.com
    - https://falconllm.tii.ae
    - https://www.midjourney.com
    - https://accent.gmu.edu
    - https://www.crcv.ucf.edu/data/UCF101.php
    - https://www.pinecone.io/learn/series/faiss/locality-sensitive-hashing
    linkcheck_allowed_redirects:
      https://doi.org/.*/.*: https://.*
      https://codespaces.new/.*: https://github.com/login.*
      https://youtu.be/.*: https://www.youtube.com/watch\?v=.*&feature=youtu.be
      https://.*.substack.com/i/\d+/.*: https://.*.substack.com/p/.*
      https://docs.bentoml.org: https://docs.bentoml.com/en/latest
      https://mozilla.org/MPL/2.0: https://www.mozilla.org/en-US/MPL/2.0
      https://mxnet.apache.org: https://mxnet.apache.org/versions/[\d.]+/.*
      https://gpt4all.io: https://gpt4all.io/index.html
    html_last_updated_fmt: '%d %b %Y'
    jblatex_show_tocs: false
    bibtex_reference_style: label
bibtex_bibfiles: [references.bib] # citations
latex: # for PDF builds
  latex_documents:
    targetname: book.tex
execute:
  execute_notebooks: force  # re-exec on each build (https://jupyterbook.org/content/execute.html)
