# Book settings (https://jupyterbook.org/customize/config.html)
title: State of Open Source AI Book
author: Prem AI
copyright: 2023 CC-BY-4.0 (text) & Apache-2.0 (code)
logo: https://static.premai.io/logo.png
repository:
  url: https://github.com/premAI-io/state-of-open-source-ai
  branch: main
only_build_toc_files: true
exclude_patterns: [.github/*]
html:
  baseurl: http://localhost:8000
  favicon: assets/favicon.ico
  use_edit_page_button: true
  use_repository_button: true
  announcement: ⚠️ work in progress; please don't share externally
  comments:
    utterances:
      issue-term: pathname
      label: question
      repo: premAI-io/state-of-open-source-ai
      theme: preferred-color-scheme
parse:
  myst_substitutions:
    repo_url: https://github.com/premAI-io/state-of-open-source-ai
    baseurl: http://localhost:8000
    # hack to get utteranc.es to render (needs a `div.section` element)
    comments: <div class="section"></div>
  myst_enable_extensions: # https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html
  # needs myst-parser>=0.19 <- https://github.com/executablebooks/MyST-NB/issues/530
  #- attrs_block
  #- attrs_inline
  - deflist
  - dollarmath
  - html_admonition
  - linkify
  - replacements
  - smartquotes
  - substitution
  - tasklist
sphinx:
  extra_extensions:
  - sphinxemoji.sphinxemoji
  config:
    html_js_files:
    - [https://plausible.io/js/script.js, {defer: defer, data-domain: book.premai.io}]
    bibtex_reference_style: label
    linkcheck_ignore:
    - http://localhost:8000
    - https://github.com/imaurer/awesome-decentralized-llm#.*
    - https://gist.github.com/veekaybee/be375ab33085102f9027853128dc5f0e#.*
    - https://github.com/premAI-io/state-of-open-source-ai # TODO: remove
    - https://contrib.rocks # TODO: remove
    linkcheck_allowed_redirects:
      https://codespaces.new/.*: https://github.com/login.*
      https://youtu.be/.*: https://www.youtube.com/watch\?v=.*&feature=youtu.be
      https://.*.substack.com/i/\d+/.*: https://.*.substack.com/p/.*
      https://docs.bentoml.org: https://docs.bentoml.com/en/latest
bibtex_bibfiles: [references.bib] # citations
latex: # for PDF builds
  latex_documents:
    targetname: book.tex
execute:
  execute_notebooks: force  # re-exec on each build (https://jupyterbook.org/content/execute.html)
