# see https://github.com/actions/starter-workflows/blob/main/pages/jekyll.yml
name: build & deploy site
on:
  push:
  workflow_dispatch:
permissions:
  # allow GITHUB_TOKEN to deploy to GitHub Pages
  contents: read
  pages: write
  id-token: write
concurrency: {group: "pages", cancel-in-progress: true}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with: {python-version: '3.x'}
    - id: pages
      uses: actions/configure-pages@v3
    - run: pip install -r requirements.txt
    - name: jupyter-book build
      run: |
        sed -ri 's#^(\s*baseurl:).*#\1 ${{ steps.pages.outputs.base_url }}#g' _config.yml
        # https://jupyterbook.org/en/stable/reference/cli.html
        jupyter-book build --warningiserror --nitpick .
    - uses: actions/upload-pages-artifact@v2
      with: {path: _build/html}
  deploy:
    if: github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
    - id: deployment
      uses: actions/deploy-pages@v2
